/**
 * Canonical Stellar testnet addresses for technical docs and local env defaults.
 */
export const TESTNET_CONTRACTS = {
  poolManager: "CDSOHQQNPLBEMH6WBC6646IH4TJ4SYWLICP6XWJTB7CARWGWPMCPHJAS",
  paymentPool: "GATXUXOFATDQXLKJCIU7G22V5NNUE7J5OP3KJKMJNBAPRM5VYQ3K7DKN",
  /** Circle CCTP on Stellar testnet — https://developers.circle.com/cctp */
  cctp: {
    tokenMessengerMinter: "CDNG7HXAPBWICI2E3AUBP3YZWZELJLYSB6F5CC7WLDTLTHVM74SLRTHP",
    messageTransmitter: "CBJ6MTCKKZG73PMDZCJMSFRD7DQEMI4FKDH7CGDSV4W6FHCRBCQAVVJY",
    cctpForwarder: "CA66Q2WFBND6V4UEB7RD4SAXSVIWMD6RA4X3U32ELVFGXV5PJK4T4VSZ",
    usdc: "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA",
  },
} as const;
